# Generated by Django 4.2.16 on 2025-02-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_school_registration', '0002_alter_student_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='instrument',
            field=models.CharField(choices=[('', 'Select an Instrument'), ('VL', 'Violin'), ('GT', 'Guitar'), ('BS', 'Bass'), ('DR', 'Drums'), ('VC', 'Vocals')], max_length=2),
        ),
    ]
