# Generated by Django 4.2.16 on 2025-02-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_school_registration', '0003_alter_student_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='instrument',
            field=models.CharField(choices=[('VL', 'Violin'), ('GT', 'Guitar'), ('BS', 'Bass'), ('DR', 'Drums'), ('VC', 'Vocals')], max_length=2),
        ),
    ]
