# Generated by Django 4.2.16 on 2025-02-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_school_registration', '0005_alter_student_days_alter_student_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='days',
            field=models.JSONField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')]),
        ),
    ]
