# Generated by Django 4.2.16 on 2025-02-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_school_registration', '0007_day_alter_student_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='day_name',
        ),
        migrations.AddField(
            model_name='day',
            name='name',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='', max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='student',
            name='days',
        ),
        migrations.AddField(
            model_name='student',
            name='days',
            field=models.ManyToManyField(to='music_school_registration.day'),
        ),
    ]
