# Generated by Django 4.2.16 on 2025-02-16 20:24

from django.db import migrations

def populate_days(apps, schema_editor):
    Day = apps.get_model('music_school_registration', 'Day')
    
    DAYS_CHOICES = [
        ('MON', 'Monday'),
        ('TUE', 'Tuesday'),
        ('WED', 'Wednesday'),
        ('THU', 'Thursday'),
        ('FRI', 'Friday'),
        ('SAT', 'Saturday'),
        ('SUN', 'Sunday'),
    ]
    
    for day_code, _ in DAYS_CHOICES:
        Day.objects.create(name=day_code)

def reverse_populate(apps, schema_editor):
    Day = apps.get_model('music_school_registration', 'Day')
    Day.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('music_school_registration', '0008_remove_day_day_name_day_name_remove_student_days_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_days, reverse_populate),
    ]
