# Generated by Django 4.2.16 on 2024-09-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_Admission_Form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeadmission',
            name='postal',
            field=models.CharField(max_length=10),
        ),
    ]
