# Generated by Django 4.2.16 on 2024-09-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_Admission_Form', '0002_alter_collegeadmission_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeadmission',
            name='emrg_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='collegeadmission',
            name='emrg_fname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='collegeadmission',
            name='emrg_lname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='collegeadmission',
            name='english',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='collegeadmission',
            name='list_lang',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='collegeadmission',
            name='relationship',
            field=models.CharField(default='', max_length=100),
        ),
    ]
