# Generated by Django 4.2.16 on 2024-09-19 09:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('College_Admission_Form', '0003_collegeadmission_emrg_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeadmission',
            name='emrg_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', help_text='Enter your emergancy number', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='collegeadmission',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', help_text='Enter phone number with country code', max_length=128, region=None),
        ),
    ]
