# Generated by Django 5.0.4 on 2024-09-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_use', models.BooleanField()),
                ('ppl_recomd', models.BooleanField()),
                ('suggestions', models.TextField(max_length=500)),
                ('satisfaction', models.CharField(choices=[('VS', 'Very Satisified'), ('V', 'Satisfied'), ('N', 'Neutral'), ('U', 'Unsitisfied'), ('UV', 'Very Unsitisfied')], default='N', max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('eamil', models.EmailField(max_length=254)),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
