# Generated by Django 5.0.4 on 2024-09-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackmodel',
            old_name='prod_use',
            new_name='first_use',
        ),
    ]
