# Generated by Django 5.0.4 on 2024-09-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rename_prod_use_feedbackmodel_first_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='first_use',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
    ]
