# Generated by Django 5.0.4 on 2024-09-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedbackmodel_first_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackmodel',
            old_name='eamil',
            new_name='email',
        ),
    ]
