# Generated by Django 4.2.16 on 2024-09-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_rename_eamil_feedbackmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='first_use',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='ppl_recomd',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
